<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AMICHAITO1-HHS" ignored="0" name="Test-class test 1" tests="10" failures="9" timestamp="18 Apr 2019 07:35:29 GMT" time="156.824" errors="0">
  <testcase name="initialOfferQuestions" time="20.146" classname="TestNG.sanityAllOptions"/>
  <testcase name="initialOfferScreen" time="20.421" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in INITIAL OFFER SCREEN QUESTION">
      <![CDATA[java.lang.Exception: Failed in INITIAL OFFER SCREEN QUESTION
at TestNG.sanityAllOptions.initialOfferScreen(sanityAllOptions.java:296)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- initialOfferScreen -->
  <testcase name="callMeWizard1" time="0.018" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in ***Call me wizard 1***">
      <![CDATA[java.lang.Exception: Failed in ***Call me wizard 1***
at TestNG.sanityAllOptions.callMeWizard1(sanityAllOptions.java:357)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- callMeWizard1 -->
  <testcase name="finalOfferQuestions" time="20.34" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER QUESTIONS">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER QUESTIONS
at TestNG.sanityAllOptions.finalOfferQuestions(sanityAllOptions.java:547)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferQuestions -->
  <testcase name="finalOfferScreen" time="20.2" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER screen">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER screen
at TestNG.sanityAllOptions.finalOfferScreen(sanityAllOptions.java:579)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferScreen -->
  <testcase name="callMeWizard2" time="0.016" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in call me wizard #2">
      <![CDATA[java.lang.Exception: Failed in call me wizard #2
at TestNG.sanityAllOptions.callMeWizard2(sanityAllOptions.java:611)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- callMeWizard2 -->
  <testcase name="covers" time="20.271" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in COVERS screen">
      <![CDATA[java.lang.Exception: Failed in COVERS screen
at TestNG.sanityAllOptions.covers(sanityAllOptions.java:640)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- covers -->
  <testcase name="payments" time="20.291" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in PAYMENTS screen">
      <![CDATA[java.lang.Exception: Failed in PAYMENTS screen
at TestNG.sanityAllOptions.payments(sanityAllOptions.java:730)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- payments -->
  <testcase name="iframeCreditGuard" time="10.016" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed in Iframe CreditGuard">
      <![CDATA[java.lang.Exception: Failed in Iframe CreditGuard
at TestNG.sanityAllOptions.iframeCreditGuard(sanityAllOptions.java:770)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- iframeCreditGuard -->
  <testcase name="thankYouPage" time="25.066" classname="TestNG.sanityAllOptions">
    <failure type="java.lang.Exception" message="Failed to display thank you page">
      <![CDATA[java.lang.Exception: Failed to display thank you page
at TestNG.sanityAllOptions.thankYouPage(sanityAllOptions.java:785)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- thankYouPage -->
</testsuite> <!-- Test-class test 1 -->
